export const items = [
  "Advanced Technical Manual",
  "Ancient Civilization Core",
  "Aquatic Pal Fluids",
  "Arrow",
  "Beautiful Flower",
  "Berry Seeds",
  "Bone",
  "Broncherry Meat",
  "Cake",
  "Caprity Meat",
  "Caramel Cotton Candy",
  "Carbon Fiber",
  "Carrot",
  "Carrot Seeds",
  "Chikipi Poultry",
  "Cloth",
  "Coal",
  "Copper Key",
  "Coralum Ore",
  "Cotton Candy",
  "Crude Oil",
  "Dark Fragment",
  "Dazzi Cloud",
  "Diamond",
  "Dog Coin",
  "Egg",
  "Eikthyrdeer Venison",
  "Electric Organ",
  "Elizabee's Staff",
  "Emerald",
  "Fiber",
  "Flame Organ",
  "Galeclaw Poultry",
  "Giant Pal Soul",
  "Gloopie Tentacle",
  "Gold Coin",
  "Gumoss Leaf",
  "Gunpowder",
  "Hardwood",
  "Hexolite",
  "High Quality Cloth",
  "High Quality Pal Oil",
  "High Quality Recovery Meds",
  "Honey",
  "Horn",
  "Ice Organ",
  "Ingot",
  "Innovative Technical Manual",
  "Katress Hair",
  "Killamari Tentacle",
  "Lamball Mutton",
  "Large Pal Soul",
  "Leather",
  "Leezpunk Crest",
  "Lettuce Seeds",
  "Low Grade Medical Supplies",
  "Mammorest Meat",
  "Medium Pal Soul",
  "Memory Wiping Medicine",
  "Meteorite Fragment",
  "Milk",
  "Mozzarina Meat",
  "Munchill Meat",
  "Mushroom",
  "Mysterious Mushroom",
  "Nightstar Sand",
  "Onion Seeds",
  "Ore",
  "Paldium Fragment",
  "Penking Plume",
  "Plasteel",
  "Potato Seeds",
  "Predator Core",
  "Pure Quartz",
  "Raw Dumud",
  "Raw Kelpsea",
  "Red Berries",
  "Reindrix Venison",
  "Ribbuny Ribbon",
  "Ruby",
  "Rushoar Pork",
  "Sapphire",
  "Silver Key",
  "Skutlass Sashimi",
  "Small Pal Soul",
  "Soralite",
  "Strange Juice",
  "Suspicious Juice",
  "Swee Hair",
  "Thermal Core",
  "Tocotoco Feather",
  "Tomato Seeds",
  "Training Manual (XL)",
  "Venom Gland",
  "Wheat Seeds",
  "Wool",
];
