export const items = [
  "Arrow",
  "Beautiful Flower",
  "Berry Seeds",
  "Bone",
  "Broncherry Meat",
  "Cake",
  "Caprity Meat",
  "Carbon Fiber",
  "Chikipi Poultry",
  "Cloth",
  "Coal",
  "Copper Key",
  "Cotton Candy",
  "Diamond",
  "Egg",
  "Eikthyrdeer Venison",
  "Electric Organ",
  "Elizabees staff",
  "Fiber",
  "Flame Organ",
  "Galeclaw Poultry",
  "Gold Coin",
  "Gumoss Leaf",
  "Gunpowder",
  "High Grade Technical Manual",
  "High Quality Cloth",
  "High Quality Pal Oil",
  "Honey",
  "Horn",
  "Ice Organ",
  "Ingot",
  "Innovative Technical Manual",
  "Katress Hair",
  "Lamball Mutton",
  "Large Pal Soul",
  "Leather",
  "Lettuce Seeds",
  "Low Grade Medical Supplies",
  "Mammorest Meat",
  "Medium Pal Soul",
  "Milk",
  "Mozzarina Meat",
  "Mushroom",
  "Ore",
  "Pal Fluids",
  "Pal Metal Ingot",
  "Paldium Fragment",
  "Penking Plume",
  "Polymer",
  "Pure Quartz",
  "Raw Dumud",
  "Raw Kelpsea",
  "Red Berries",
  "Reindrix Venison",
  "Ruby",
  "Rushoar Pork",
  "Silver Key",
  "Small Pal Soul",
  "Strange Juice",
  "Suspicious Juice",
  "Tocotoco Feather",
  "Tomato Seeds",
  "Venom Gland",
  "Wheat Seeds",
  "Wool",
];
